export enum EnvVariables {
  DISCORD_TOKEN = 'DISCORD_TOKEN',
  DISCORD_CLIENT_ID = 'DISCORD_CLIENT_ID',
  DISCORD_GUILD_ID = 'DISCORD_GUILD_ID',
  ADMIN_ROLE_ID = 'ADMIN_ROLE_ID',
  REGISTERED_ID = 'REGISTERED_ID',
  // #Algorand
  PURESTAKE_API_TOKEN = 'PURESTAKE_API_TOKEN',
  CREATOR_ADDRESSES = 'CREATOR_ADDRESSES',
}
